name: CyberEnte
version: '${version}'

main: de.datenente.cyberente.CyberEnte
api-version: '1.21'
folia-supported: true

load: STARTUP

depend: [CyberEnte-Extended]

website: https://www.e-duck.de
description: Ein maßgeschneidertes Minecraft Paper-Plugin für den privaten CyberEnte-Server.
authors: [CyberEnte, KeksGauner]
