name: CyberEnte
version: '1.3-SNAPSHOT'

main: de.datenente.cyberente.CyberEnte
api-version: '1.21'

load: STARTUP

depend: [CyberEnte-Extended]

description: Ein maßgeschneidertes Minecraft Paper-Plugin für den privaten CyberEnte-Server.
authors: [CyberEnte, KeksGauner]
