name: CyberEnte
version: '1.1-SNAPSHOT'

main: de.datenente.cyberente.CyberEnte
api-version: '1.21'

sof: [CyberEnte-Extended]

description: Ein maßgeschneidertes Minecraft Paper-Plugin für den privaten CyberEnte-Server.
authors: [CyberEnte, KeksGauner]
